{
  pkgs,
  ...
}:

{
  programs.nix-ld.enable = true;
  programs.nix-ld.libraries = with pkgs; [
    alsa-lib
    at-spi2-atk
    at-spi2-core
    atk
    bzip2
    cairo
    curl
    dbus
    desktop-file-utils
    expat
    fontconfig
    freeglut
    freetype
    fribidi
    fuse3
    gdk-pixbuf
    glew110
    glib
    gmp
    gst_all_1.gst-plugins-base
    gst_all_1.gst-plugins-ugly
    gst_all_1.gstreamer
    harfbuzz
    icu
    keyutils.lib
    libcaca
    libcanberra
    libcap
    libdbusmenu
    libdrm
    libgcrypt
    libGL
    libGLU
    libgpg-error
    libidn
    libjpeg
    libogg
    libpng12
    librsvg
    libsamplerate
    libtheora
    libtiff
    libusb1
    libuuid
    libvdpau
    libvorbis
    libvpx
    libxkbcommon
    libxml2
    mesa
    nspr
    nss
    openssl
    p11-kit
    pango
    pixman
    python3
    SDL2
    SDL2_image
    SDL2_mixer
    SDL2_ttf
    speex
    stdenv.cc.cc
    stdenv.cc.cc.lib
    tbb
    udev
    vulkan-loader
    xorg.libICE
    xorg.libpciaccess
    xorg.libSM
    xorg.libX11
    xorg.libxcb
    xorg.libXcomposite
    xorg.libXcursor
    xorg.libXdamage
    xorg.libXext
    xorg.libXfixes
    xorg.libXft
    xorg.libXi
    xorg.libXinerama
    xorg.libXmu
    xorg.libXrandr
    xorg.libXrender
    xorg.libXScrnSaver
    xorg.libXt
    xorg.libXtst
    xorg.libXxf86vm
    xorg.xcbutil
    xorg.xcbutilimage
    xorg.xcbutilkeysyms
    xorg.xcbutilrenderutil
    xorg.xcbutilwm
    xorg.xkeyboardconfig
    xz
    zlib
  ];
}
