{
  config,
  pkgs,
  ...
}:

{
  programs.nix-ld.enable = true;
  programs.nix-ld.libraries = with pkgs; [
    alsa-lib
    bzip2
    cairo
    cups
    expat
    glib
    gst_all_1.gst-plugins-base
    gst_all_1.gst-plugins-ugly
    gst_all_1.gstreamer
    harfbuzz
    icu
    libappindicator-gtk2
    libdrm
    libgcrypt
    libgbm
    libGL
    libva
    libxml2
    mesa
    nss
    openssl
    p11-kit
    python3
    stdenv.cc.cc
    stdenv.cc.cc.lib
    udev
    vulkan-loader
    xorg.libICE
    xorg.libpciaccess
    xorg.libSM
    xorg.libX11
    xorg.libxcb
    xorg.libXcomposite
    xorg.libXcursor
    xorg.libXdamage
    xorg.libXext
    xorg.libXfixes
    xorg.libXft
    xorg.libXi
    xorg.libXinerama
    xorg.libXmu
    xorg.libXrandr
    xorg.libXrender
    xorg.libXScrnSaver
    xorg.libXt
    xorg.libXtst
    xorg.libXxf86vm
    xorg.xcbutil
    xorg.xcbutilimage
    xorg.xcbutilkeysyms
    xorg.xcbutilrenderutil
    xorg.xcbutilwm
    xorg.xkeyboardconfig
    xz
    zlib
  ];
}
